CREATE USER ISER IDENTIFIED BY password;

GRANT CONNECT, RESOURCE TO ISER;

ALTER SESSION SET CURRENT_SCHEMA = ISER;

CREATE TABLESPACE ISER_DATA DATAFILE '/opt/oracle/oradata/XE/iser_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE ISER_TEMP TEMPFILE '/opt/oracle/oradata/XE/iser_temp.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER USER ISER DEFAULT TABLESPACE ISER_DATA TEMPORARY TABLESPACE ISER_TEMP QUOTA UNLIMITED ON ISER_DATA;

